/**
 * Generic text-template post for G-code style controllers (not used for the HOMAG, which gets
 * native MPR). Template posts and script posts (M2.10, PST-02) both read `postInput(...)`, so there
 * is one post path for text programs. Our own template format:
 *
 *   [file]      ext=nc  decimals=3  modal=F
 *   [start] [toolchange] [rapid] [feed] [arc_cw] [arc_ccw] [drill] [peck] [comment] [end]
 *
 * Section bodies are lines with {NAME} placeholders (X Y Z I J F S T R Q TEXT NAME TOOLNAME).
 * {NAME:4} forces 4 decimals. A line starting with "?NAME " is written only when NAME is set.
 * Words listed in `modal` are dropped when their value did not change.
 */
import { simpleMoves, type FeedKind, type Toolpath } from './toolpath'
import { planeToCyl, ROTARY_LETTER } from './rotary/frame'
import type { RotaryAxis } from './types'

export interface PostTemplate {
  name: string
  text: string
}

export const SAMPLE_TEMPLATE: PostTemplate = {
  name: 'Generic ISO router (sample)',
  text: `[file]
ext=nc
decimals=3
modal=F
[start]
%
({NAME})
(GENERATED BY CABINET STUDIO - NOT MACHINE-VALIDATED)
G21 G90 G17
[toolchange]
(T{T} {TOOLNAME})
T{T} M6
S{S} M3
[rapid]
G0 X{X} Y{Y} Z{Z}
[feed]
G1 X{X} Y{Y} Z{Z} F{F}
[arc_cw]
G2 X{X} Y{Y} Z{Z} I{I} J{J} F{F}
[arc_ccw]
G3 X{X} Y{Y} Z{Z} I{I} J{J} F{F}
[drill]
G81 X{X} Y{Y} Z{Z} R{R} F{F}
G80
[peck]
G83 X{X} Y{Y} Z{Z} R{R} Q{Q} F{F}
G80
[comment]
({TEXT})
[end]
M5
G0 Z50
M30
%
`,
}

interface Parsed {
  ext: string
  decimals: number
  modal: Set<string>
  sections: Record<string, string[]>
}

export function parseTemplate(text: string): Parsed {
  const out: Parsed = { ext: 'nc', decimals: 3, modal: new Set(), sections: {} }
  let cur = ''
  for (const raw of text.split(/\r?\n/)) {
    const m = /^\[([a-z_]+)\]\s*$/.exec(raw.trim())
    if (m) {
      cur = m[1]
      out.sections[cur] = []
      continue
    }
    if (cur === 'file') {
      const kv = /^(\w+)\s*=\s*(.*)$/.exec(raw.trim())
      if (!kv) continue
      if (kv[1] === 'ext') out.ext = kv[2]
      if (kv[1] === 'decimals') out.decimals = Number(kv[2]) || 3
      if (kv[1] === 'modal') kv[2].split(/[ ,]+/).filter(Boolean).forEach((w) => out.modal.add(w.toUpperCase()))
      continue
    }
    if (cur && raw.length) out.sections[cur].push(raw)
  }
  return out
}

/**
 * What every text post gets (M2.10, PST-02): the toolpaths in run order as plain data, Z measured
 * from the part's top (`zTop` added), feeds in mm/min already worked out per move, arc centres
 * both absolute and relative to the move's start (I, J). The template post below and script posts
 * (sandboxed plugins) read the same thing, so the two can be compared exactly.
 */
export interface PostToolInfo {
  number: number
  name: string
  diameter: number
}
/**
 * Rotary operations' moves (M3.3) also carry `a`: the angle of the part under the tool in degrees
 * (0 = straight up, right-handed about the axis, counting on past 360: never wrapped), and feed
 * moves `len`: how far the tool's tip travels on the part (mm), for posts that write inverse-time
 * feeds.
 */
export type PostMove =
  | { t: 'rapid'; x: number; y: number; z: number; a?: number }
  | { t: 'feed'; x: number; y: number; z: number; f: number; kind: FeedKind; a?: number; len?: number }
  | { t: 'arc'; x: number; y: number; z: number; i: number; j: number; cx: number; cy: number; ccw: boolean; f: number }
  | { t: 'drill'; x: number; y: number; z: number; r: number; peck: number; dwell: number; f: number }
export interface PostOp {
  name: string
  kind: Toolpath['kind']
  tool: PostToolInfo | null
  rpm: number
  moves: PostMove[]
  /**
   * Rotary operation (M3.3): the part axis it turns about and the machine's letter for that axis.
   * Its moves are against the rotary axis, not the part's corner: for an axis along X, x is the
   * position along the axis (part coordinate), y = 0 (the tool over the axis) and z the tip's
   * distance from the axis; along Y the same with x and y swapped; along Z, z is along the axis and
   * x the tip's distance from it. `a` gives the angle. Set the machine's work offset on the axis.
   */
  rotary?: { axis: RotaryAxis; letter: 'A' | 'B' | 'C'; blade?: { R: number; plane: 'axial' | 'ring' } }
}
export interface PostInput {
  name: string
  units: 'mm'
  part?: { length: number; width: number; thickness: number }
  ops: PostOp[]
}

export function postInput(name: string, paths: Toolpath[], opts: { zTop?: number; part?: { length: number; width: number; thickness: number } } = {}): PostInput {
  const zTop = opts.zTop ?? 0
  let x = 0
  let y = 0
  const ops = paths.map((tp): PostOp => {
    if (tp.rotary) return rotaryPostOp(tp)
    const moves: PostMove[] = []
    for (const m of simpleMoves(tp.moves)) {
      const z = m.z + zTop
      if (m.t === 'rapid') moves.push({ t: 'rapid', x: m.x, y: m.y, z })
      else if (m.t === 'feed') moves.push({ t: 'feed', x: m.x, y: m.y, z, f: Math.round((m.f === 'plunge' ? tp.feeds.plunge : tp.feeds.feed) * (m.k ?? 1)), kind: m.f })
      // arcs that plunge (helical entries) run at the plunge feed, as the toolpath and the simulator say (M2.10c fix)
      else if (m.t === 'arc') moves.push({ t: 'arc', x: m.x, y: m.y, z, i: m.cx - x, j: m.cy - y, cx: m.cx, cy: m.cy, ccw: m.ccw, f: Math.round((m.f === 'plunge' ? tp.feeds.plunge : tp.feeds.feed) * (m.k ?? 1)) })
      else moves.push({ t: 'drill', x: m.x, y: m.y, z, r: m.r + zTop, peck: m.peck, dwell: m.dwell, f: Math.round(tp.feeds.plunge) })
      x = m.x
      y = m.y
    }
    return { name: tp.name, kind: tp.kind, tool: tp.tool ? { number: tp.tool.number, name: tp.tool.name, diameter: tp.tool.diameter } : null, rpm: Math.round(tp.feeds.rpm), moves }
  })
  return { name, units: 'mm', ...(opts.part ? { part: { ...opts.part } } : {}), ops }
}

/** A rotary toolpath as post data: positions against the rotary axis, the angle in degrees. */
function rotaryPostOp(tp: Toolpath): PostOp {
  const r = tp.rotary!
  const axis = r.setup.axis
  const at = (u: number, rho: number) => (axis === 'X' ? { x: u, y: 0, z: rho } : axis === 'Y' ? { x: 0, y: u, z: rho } : { x: rho, y: 0, z: u })
  const moves: PostMove[] = []
  let prev: { u: number; theta: number; rho: number } | null = null
  for (const m of simpleMoves(tp.moves)) {
    if (m.t !== 'rapid' && m.t !== 'feed') continue
    const c = planeToCyl(r.plane, m.x, m.y, m.z)
    const a = (c.theta * 180) / Math.PI
    if (m.t === 'rapid') moves.push({ t: 'rapid', ...at(c.u, c.rho), a })
    else {
      const len = prev ? Math.hypot(c.u - prev.u, ((c.rho + prev.rho) / 2) * (c.theta - prev.theta), c.rho - prev.rho) : 0
      moves.push({ t: 'feed', ...at(c.u, c.rho), a, f: Math.round((m.f === 'plunge' ? tp.feeds.plunge : tp.feeds.feed) * (m.k ?? 1)), kind: m.f, len })
    }
    prev = c
  }
  return {
    name: tp.name,
    kind: tp.kind,
    tool: tp.tool ? { number: tp.tool.number, name: tp.tool.name, diameter: tp.tool.diameter } : null,
    rpm: Math.round(tp.feeds.rpm),
    moves,
    rotary: { axis, letter: ROTARY_LETTER[axis], ...(r.blade ? { blade: { ...r.blade } } : {}) },
  }
}

/** The template post on a post input. */
export function runTemplate(template: PostTemplate, input: PostInput): { ext: string; text: string } {
  const t = parseTemplate(template.text)
  const lines: string[] = []
  const last: Record<string, string> = {}
  const emit = (section: string, vars: Record<string, string | number | undefined>) => {
    for (const tl of t.sections[section] ?? []) {
      let ln = tl
      const cond = /^\?(\w+) /.exec(ln)
      if (cond) {
        if (vars[cond[1]] === undefined || vars[cond[1]] === '') continue
        ln = ln.slice(cond[0].length)
      }
      ln = ln.replace(/(\S*?)\{(\w+)(?::(\d+))?\}/g, (_all, prefix: string, key: string, dec?: string) => {
        const v = vars[key]
        if (v === undefined) return ''
        const s = typeof v === 'number' ? v.toFixed(dec ? Number(dec) : t.decimals) : v
        const word = (prefix || '').toUpperCase()
        if (word && t.modal.has(word)) {
          if (last[word] === s) return ''
          last[word] = s
        }
        return `${prefix}${s}`
      })
      lines.push(ln.replace(/\s+$/, '').replace(/ {2,}/g, ' '))
    }
  }
  emit('start', { NAME: input.name })
  for (const op of input.ops) {
    // a template has no rotary axis: a rotary operation's moves are never written by it (the
    // export checker refuses such a program; this keeps a preview from showing them as X Y Z)
    if (op.rotary) {
      emit('comment', { TEXT: `${op.name}: ROTARY (${op.rotary.letter} AXIS) - NOT WRITTEN BY A TEMPLATE POST` })
      continue
    }
    if (op.tool) emit('toolchange', { T: String(op.tool.number), S: String(op.rpm), TOOLNAME: op.tool.name })
    emit('comment', { TEXT: op.name })
    for (const m of op.moves) {
      if (m.t === 'rapid') emit('rapid', { X: m.x, Y: m.y, Z: m.z })
      else if (m.t === 'feed') emit('feed', { X: m.x, Y: m.y, Z: m.z, F: String(m.f) })
      else if (m.t === 'arc') emit(m.ccw ? 'arc_ccw' : 'arc_cw', { X: m.x, Y: m.y, Z: m.z, I: m.i, J: m.j, F: String(m.f) })
      else emit(m.peck > 0 ? 'peck' : 'drill', { X: m.x, Y: m.y, Z: m.z, R: m.r, Q: m.peck, F: String(m.f) })
    }
  }
  emit('end', {})
  return { ext: t.ext, text: lines.join('\r\n') + '\r\n' }
}

export function runPost(template: PostTemplate, name: string, paths: Toolpath[], zTop = 0): { ext: string; text: string } {
  return runTemplate(template, postInput(name, paths, { zTop }))
}
