/**
 * Generic text-template post for G-code style controllers (not used for the HOMAG, which gets
 * native MPR). Our own template format:
 *
 *   [file]      ext=nc  decimals=3  modal=F
 *   [start] [toolchange] [rapid] [feed] [arc_cw] [arc_ccw] [drill] [peck] [comment] [end]
 *
 * Section bodies are lines with {NAME} placeholders (X Y Z I J F S T R Q TEXT NAME TOOLNAME).
 * {NAME:4} forces 4 decimals. A line starting with "?NAME " is written only when NAME is set.
 * Words listed in `modal` are dropped when their value did not change.
 */
import type { Move, Toolpath } from './toolpath'

export interface PostTemplate {
  name: string
  text: string
}

export const SAMPLE_TEMPLATE: PostTemplate = {
  name: 'Generic ISO router (sample)',
  text: `[file]
ext=nc
decimals=3
modal=F
[start]
%
({NAME})
(GENERATED BY CABINET STUDIO - NOT MACHINE-VALIDATED)
G21 G90 G17
[toolchange]
(T{T} {TOOLNAME})
T{T} M6
S{S} M3
[rapid]
G0 X{X} Y{Y} Z{Z}
[feed]
G1 X{X} Y{Y} Z{Z} F{F}
[arc_cw]
G2 X{X} Y{Y} Z{Z} I{I} J{J} F{F}
[arc_ccw]
G3 X{X} Y{Y} Z{Z} I{I} J{J} F{F}
[drill]
G81 X{X} Y{Y} Z{Z} R{R} F{F}
G80
[peck]
G83 X{X} Y{Y} Z{Z} R{R} Q{Q} F{F}
G80
[comment]
({TEXT})
[end]
M5
G0 Z50
M30
%
`,
}

interface Parsed {
  ext: string
  decimals: number
  modal: Set<string>
  sections: Record<string, string[]>
}

export function parseTemplate(text: string): Parsed {
  const out: Parsed = { ext: 'nc', decimals: 3, modal: new Set(), sections: {} }
  let cur = ''
  for (const raw of text.split(/\r?\n/)) {
    const m = /^\[([a-z_]+)\]\s*$/.exec(raw.trim())
    if (m) {
      cur = m[1]
      out.sections[cur] = []
      continue
    }
    if (cur === 'file') {
      const kv = /^(\w+)\s*=\s*(.*)$/.exec(raw.trim())
      if (!kv) continue
      if (kv[1] === 'ext') out.ext = kv[2]
      if (kv[1] === 'decimals') out.decimals = Number(kv[2]) || 3
      if (kv[1] === 'modal') kv[2].split(/[ ,]+/).filter(Boolean).forEach((w) => out.modal.add(w.toUpperCase()))
      continue
    }
    if (cur && raw.length) out.sections[cur].push(raw)
  }
  return out
}

export function runPost(template: PostTemplate, name: string, paths: Toolpath[], zTop = 0): { ext: string; text: string } {
  const t = parseTemplate(template.text)
  const lines: string[] = []
  const last: Record<string, string> = {}
  const emit = (section: string, vars: Record<string, string | number | undefined>) => {
    for (const tl of t.sections[section] ?? []) {
      let ln = tl
      const cond = /^\?(\w+) /.exec(ln)
      if (cond) {
        if (vars[cond[1]] === undefined || vars[cond[1]] === '') continue
        ln = ln.slice(cond[0].length)
      }
      ln = ln.replace(/(\S*?)\{(\w+)(?::(\d+))?\}/g, (_all, prefix: string, key: string, dec?: string) => {
        const v = vars[key]
        if (v === undefined) return ''
        const s = typeof v === 'number' ? v.toFixed(dec ? Number(dec) : t.decimals) : v
        const word = (prefix || '').toUpperCase()
        if (word && t.modal.has(word)) {
          if (last[word] === s) return ''
          last[word] = s
        }
        return `${prefix}${s}`
      })
      lines.push(ln.replace(/\s+$/, '').replace(/ {2,}/g, ' '))
    }
  }
  emit('start', { NAME: name })
  let x = 0
  let y = 0
  for (const tp of paths) {
    if (tp.tool) emit('toolchange', { T: String(tp.tool.number), S: String(Math.round(tp.feeds.rpm)), TOOLNAME: tp.tool.name })
    emit('comment', { TEXT: tp.name })
    for (const m of tp.moves as Move[]) {
      const Z = m.z + zTop
      if (m.t === 'rapid') emit('rapid', { X: m.x, Y: m.y, Z })
      else if (m.t === 'feed') emit('feed', { X: m.x, Y: m.y, Z, F: String(Math.round(m.f === 'plunge' ? tp.feeds.plunge : tp.feeds.feed)) })
      else if (m.t === 'arc') emit(m.ccw ? 'arc_ccw' : 'arc_cw', { X: m.x, Y: m.y, Z, I: m.cx - x, J: m.cy - y, F: String(Math.round(tp.feeds.feed)) })
      else emit(m.peck > 0 ? 'peck' : 'drill', { X: m.x, Y: m.y, Z, R: m.r + zTop, Q: m.peck, F: String(Math.round(tp.feeds.plunge)) })
      x = m.x
      y = m.y
    }
  }
  emit('end', {})
  return { ext: t.ext, text: lines.join('\r\n') + '\r\n' }
}
