/**
 * M3.3 rotary output (acceptance: "output only through a script post for a machine model with a
 * rotary axis; the N-200 export refuses it"). The sample rotary script post writes a turned part's
 * program for a router whose machine model declares an A axis, only with every switch on and the
 * grant; everything else is refused with its reason.
 */
import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { defaultOp } from '@/cam/ops'
import { PluginHost } from '@/cam/plugin/host'
import { pluginRecord } from '@/cam/plugin/manifest'
import { planPartPost, runScriptPost } from '@/cam/plugin/posts'
import type { PluginRecord } from '@/cam/plugin/types'
import { postInput, runTemplate, SAMPLE_TEMPLATE } from '@/cam/post'
import { planeToCyl } from '@/cam/rotary/frame'
import { generateOp, pathKey, simpleMoves, type Toolpath } from '@/cam/toolpath'
import type { CamPart } from '@/cam/types'
import { PLACEHOLDER_N200_MODEL, rotaryAxisOf, withRotaryAxis } from '@/core/machineModel'
import { MAIN_MACHINE, newMachineSetup } from '@/core/machines'
import { runJob } from '@/core/pipeline'
import type { AppData, Job, MachineModel, MachineSetup } from '@/core/types'
import { checkTextPost } from '@/core/validator'
import { data } from './helpers'
import { columnPart, legPart, rotaryOp } from './rotary-fixtures'

const POST = fs.readFileSync(path.resolve(import.meta.dirname, '../examples/plugins/rotary-4axis-post.js'), 'utf8')
const NOW = '2026-10-07T00:00:00.000Z'
const say = (s: string) => process.stdout.write(`  [rotary post] ${s}\n`)

function install(code: string, grants: PluginRecord['grants'] = {}): PluginRecord {
  return { ...pluginRecord(code, 'test', NOW), grants, enabled: true }
}

/** A router with a rotary axis (machine model: X Y Z and A, all the way round many times). */
function rotaryRouter(d: AppData, opts: { axes?: MachineModel['axes']; rotary?: boolean; saw?: boolean; post?: MachineSetup['post'] } = {}): MachineSetup {
  const m = newMachineSetup(d, { name: 'Rotary router', from: 'main' })
  m.profile.model = '4-axis router (example)'
  const base = withRotaryAxis(structuredClone(PLACEHOLDER_N200_MODEL), 'A')
  m.profile.physical = { ...base, axes: opts.axes ?? base.axes, capabilities: { ...base.capabilities, rotary: opts.rotary ?? true, saw: opts.saw ?? false } }
  m.post = opts.post ?? { kind: 'script', plugin: 'rotary-4axis-post', post: 'rotary-4axis' }
  d.machines = [...(d.machines ?? []).filter((x) => x.id !== m.id), m]
  return m
}

function flutedColumn(): CamPart {
  const { part, flutes } = columnPart()
  return { ...part, ops: [rotaryOp('wrap', { id: 'flutes', toolId: 't105', geometry: flutes, levels: { safeZ: 20, rapidZ: 5, depth: 2.5, through: false, stockZ: 0, passDepth: 0 } })] }
}

const codes = (issues: { code: string; severity: string }[]) => issues.filter((i) => i.severity === 'error').map((i) => i.code)

describe('M3.3 rotary programs through a script post', () => {
  it('writes the fluted column for a router with an A axis: every move\'s X, Z and A as the toolpath has it', async () => {
    const d = data()
    const router = rotaryRouter(d)
    const h = await PluginHost.start(install(POST))
    d.plugins = [{ ...install(POST, { machineOutput: true }), contributes: h.contributes }]
    const part = flutedColumn()
    // switches off: shown, not written, each switch named
    const off = planPartPost(d, router.id, part)
    expect(off.writable).toBe(false)
    expect(codes(off.issues)).toEqual(['POST_OUTPUT_OFF', 'POST_ROTARY_OFF'])
    d.settings.features = { ...d.settings.features, scriptPostOutput: true }
    expect(codes(planPartPost(d, router.id, part).issues)).toEqual(['POST_ROTARY_OFF'])
    d.settings.features = { ...d.settings.features, rotaryPostOutput: true }
    const on = planPartPost(d, router.id, part)
    expect(codes(on.issues)).toEqual([])
    expect(on.writable).toBe(true)
    expect(on.input.ops[0].rotary).toEqual({ axis: 'X', letter: 'A' })
    const text = (await runScriptPost(h, 'rotary-4axis', on.input)).text
    expect(text).toMatch(/^%\r\n\(Fluted column\)\r\n\(GENERATED BY CABINET STUDIO - NOT MACHINE-VALIDATED\)/)
    expect(text).toContain('(ROTARY A ABOUT X: WORK OFFSET ON THE AXIS, A0 = TOOL STRAIGHT ABOVE)')
    // read the program back: X along the axis, Z the tip's distance from it, A the angle
    const tp = on.toolpaths[0]
    const want = [...simpleMoves(tp.moves)].map((m) => (m.t === 'rapid' || m.t === 'feed' ? planeToCyl(tp.rotary!.plane, m.x, m.y, m.z) : null)).filter((c) => c !== null)
    const got = text
      .split('\r\n')
      .map((l) => /G[01] X(-?[\d.]+) Y(-?[\d.]+) Z(-?[\d.]+) A(-?[\d.]+)/.exec(l))
      .filter((m) => m !== null)
      .map((m) => ({ x: Number(m[1]), y: Number(m[2]), z: Number(m[3]), a: Number(m[4]) }))
    expect(got.length).toBe(want.length)
    let worst = 0
    got.forEach((g, i) => {
      const w = want[i]!
      worst = Math.max(worst, Math.abs(g.x - w.u), Math.abs(g.z - w.rho), Math.abs(g.a - (w.theta * 180) / Math.PI), Math.abs(g.y))
    })
    say(`fluted column for "Rotary router" (A axis): ${got.length} moves read back, worst ${worst.toFixed(4)} (mm or °, 3 decimals written)`)
    expect(worst).toBeLessThanOrEqual(0.0005)
    // the flutes run straight along X at a fixed A, 22.5 mm from the axis, at the tool's feed
    expect(text).toContain('G94 G1 X30.000 Y0.000 Z22.500 A22.500 F2000\r\nG1 X170.000 Y0.000 Z22.500 A22.500 F5000\r\n')
    h.dispose()
  })

  it('writes the turned leg (rings round the axis, calculated in the background) with inverse-time feeds where the axis turns', async () => {
    const d = data((x) => (x.settings.features = { ...x.settings.features, scriptPostOutput: true, rotaryPostOutput: true }))
    const router = rotaryRouter(d)
    const h = await PluginHost.start(install(POST))
    d.plugins = [{ ...install(POST, { machineOutput: true }), contributes: h.contributes }]
    const { part: leg, mesh } = legPart()
    // a stretch of the taper keeps it quick
    const short: CamPart = { ...leg, rotary: { ...leg.rotary!, planes: [{ ...leg.rotary!.planes[0], start: 150, end: 170 }] } }
    const op = rotaryOp('around', { id: 'rings', toolId: 't105', stepover: 5, modelId: 'leg' })
    const part = { ...short, ops: [op] }
    // not calculated yet: refused, the program would miss it
    const early = planPartPost(d, router.id, part)
    expect(codes(early.issues)).toContain('POST_NOT_READY')
    expect(early.writable).toBe(false)
    // calculated (as the page's background worker does) for this machine's tools
    const machine = router.profile
    const tp = generateOp(op, { part, machine, meshes: new Map([['leg', mesh]]) })
    const plan = planPartPost(d, router.id, part, { paths3d: new Map([[pathKey(op, part, machine), tp]]) })
    expect(codes(plan.issues)).toEqual([])
    const text = (await runScriptPost(h, 'rotary-4axis', plan.input)).text
    const moves = plan.input.ops[0].moves
    // every feed move that turns the axis is G93 with F = feed / travel of the tip
    let checked = 0
    let lastA: number | null = null
    for (const m of moves) {
      if (m.t === 'arc' || m.t === 'drill') continue
      if (m.t === 'feed' && lastA !== null && Math.abs((m.a ?? 0) - lastA) > 1e-9) {
        expect(m.len).toBeGreaterThan(0)
        checked++
      }
      lastA = m.a ?? null
    }
    expect(checked).toBeGreaterThan(100)
    expect(text).toMatch(/G93 G1 X\S+ Y0\.000 Z\S+ A\S+ F[\d.]+/)
    expect(text).toMatch(/\r\nG94\r\nM5\r\n/)
    h.dispose()
  }, 60_000)
})

describe('M3.3 a machine model with a rotary axis', () => {
  it('sets, reads and takes away the rotary axis; the N-200 model has none', () => {
    expect(rotaryAxisOf(PLACEHOLDER_N200_MODEL)).toBeNull()
    const a = withRotaryAxis(PLACEHOLDER_N200_MODEL, 'A')
    expect(a.axes.map((x) => x.id)).toEqual(['X', 'Y', 'Z', 'A'])
    expect(rotaryAxisOf(a)).toEqual({ id: 'A', min: -36000, max: 36000 })
    const b = withRotaryAxis(a, 'B', { min: -180, max: 180 })
    expect(b.axes.map((x) => x.id)).toEqual(['X', 'Y', 'Z', 'B'])
    expect(rotaryAxisOf(b)).toEqual({ id: 'B', min: -180, max: 180 })
    const none = withRotaryAxis(b, null)
    expect(none.axes.map((x) => x.id)).toEqual(['X', 'Y', 'Z'])
    expect(none.capabilities.rotary).toBe(false)
    // the original is not changed
    expect(PLACEHOLDER_N200_MODEL.axes.map((x) => x.id)).toEqual(['X', 'Y', 'Z'])
  })
})

describe('M3.3 rotary output refused', () => {
  it('the N-200, a machine without that rotary axis, the template post, flat work mixed in, angles past the axis\'s travel, a blade without a saw unit', async () => {
    const d = data((x) => (x.settings.features = { ...x.settings.features, scriptPostOutput: true, rotaryPostOutput: true }))
    const h = await PluginHost.start(install(POST))
    d.plugins = [{ ...install(POST, { machineOutput: true }), contributes: h.contributes }]
    const part = flutedColumn()
    // the N-200 (main machine: woodWOP only), and a copy still described as one
    expect(planPartPost(d, MAIN_MACHINE, part).writable).toBe(false)
    const n200: MachineSetup = { ...newMachineSetup(d, { name: 'Copy', from: 'main' }), post: { kind: 'script', plugin: 'rotary-4axis-post', post: 'rotary-4axis' } }
    expect(codes(checkTextPost(n200, { switchOn: true, rotaryOn: true, plugin: d.plugins[0], toolpaths: planPartPost(rotaryData(d), rotaryRouterId, part).toolpaths }))).toContain('POST_N200')
    // no rotary axis in the model (capabilities say none)
    const none = rotaryData(d, { rotary: false })
    expect(planPartPost(none, rotaryRouterId, part).issues.find((i) => i.code === 'POST_UNSUPPORTED')?.message).toMatch(/has no rotary A axis in its machine model \(the part turns about X\)/)
    // a B axis only: the part turns about X
    const bOnly = rotaryData(d, { axes: [...PLACEHOLDER_N200_MODEL.axes, { id: 'B', min: -360, max: 360 }] })
    expect(planPartPost(bOnly, rotaryRouterId, part).issues.find((i) => i.code === 'POST_UNSUPPORTED')?.message).toMatch(/no rotary A axis/)
    // an A axis that turns only a quarter of the way: the flutes need more
    const quarter = rotaryData(d, { axes: [...PLACEHOLDER_N200_MODEL.axes, { id: 'A', min: 0, max: 90 }] })
    expect(planPartPost(quarter, rotaryRouterId, part).issues.find((i) => i.code === 'POST_UNSUPPORTED')?.message).toMatch(/turns the A axis from 22\.5° to 337\.5°, outside its travel \(0° to 90°\)/)
    // the built-in template post: no rotary axis; its text never carries the rotary moves
    const tmpl = rotaryData(d, { post: { kind: 'template', ...SAMPLE_TEMPLATE } })
    const tplan = planPartPost(tmpl, rotaryRouterId, part)
    expect(codes(tplan.issues)).toContain('POST_ROTARY_TEMPLATE')
    expect(tplan.writable).toBe(false)
    expect(tplan.templateText!.text).toContain('(Rotary wrapped shapes: ROTARY (A AXIS) - NOT WRITTEN BY A TEMPLATE POST)')
    expect(tplan.templateText!.text).not.toMatch(/G1 |G0 X/)
    // a flat operation on the turned part: it would be written in the flat frame
    const mixed: CamPart = { ...part, ops: [...part.ops, { ...defaultOp('engrave', part.entities.filter((e) => e.layer === 'machining').map((e) => e.id).slice(0, 1)), toolId: 't103' }] }
    const mplan = planPartPost(rotaryData(d), rotaryRouterId, mixed)
    expect(codes(mplan.issues)).toContain('POST_ROTARY_MIXED')
    // a saw blade on the rotary axis needs a saw unit in the model
    const reeds: CamPart = { ...part, ops: [{ ...part.ops[0], toolId: 't140' }] }
    expect(planPartPost(rotaryData(d), rotaryRouterId, reeds).issues.find((i) => i.code === 'POST_UNSUPPORTED')?.message).toMatch(/has no saw unit/)
    expect(codes(planPartPost(rotaryData(d, { saw: true }), rotaryRouterId, reeds).issues)).toEqual([])
    // the grant and the switches, as for any script post
    const ungranted = rotaryData(d)
    ungranted.plugins = [{ ...d.plugins[0], grants: {} }]
    expect(codes(planPartPost(ungranted, rotaryRouterId, part).issues)).toEqual(['POST_NO_GRANT'])
    h.dispose()
  })

  it('the N-200 job export refuses a turned part however its switches are set; the post input never reaches woodWOP', () => {
    const d = data((x) => (x.settings.features = { ...x.settings.features, camMprOutput: true, cam3dMprOutput: true, cam25dMprOutput: true, scriptPostOutput: true, rotaryPostOutput: true }))
    const part = flutedColumn()
    const at = '2026-01-01T00:00:00.000Z'
    const job: Job = { id: 'j', number: 'R2', name: 'Rotary', customer: '', notes: '', createdAt: at, updatedAt: at, cabinets: [], camParts: [part] }
    const r = runJob(job, d)
    expect(r.issues.filter((i) => i.code === 'CAM_ROTARY').map((i) => i.severity)).toEqual(['error'])
    expect(r.programs).toEqual([])
    // the post input of a rotary toolpath, for completeness: no zTop shift, the angle carried
    const tp = generateOp(part.ops[0], { part, machine: d.machine }) as Toolpath
    const input = postInput(part.name, [tp], { zTop: 19 })
    expect(input.ops[0].moves.every((m) => (m.t === 'rapid' || m.t === 'feed') && typeof m.a === 'number' && m.z > 0)).toBe(true)
    expect(runTemplate(SAMPLE_TEMPLATE, input).text).not.toMatch(/G1 |G0 X/)
  })
})

let rotaryRouterId = ''
/** A copy of the data with one rotary router (and its options). */
function rotaryData(d: AppData, opts: Parameters<typeof rotaryRouter>[1] = {}): AppData {
  const { plugins, ...rest } = d
  const c = structuredClone({ ...rest, machines: [] as MachineSetup[] }) as AppData
  c.plugins = plugins
  const m = rotaryRouter(c, opts)
  rotaryRouterId = m.id
  return c
}
