/**
 * M3.4 3+2 output (standing rule: rotary, 3+2 and 5-axis output only through a script post for a
 * machine model that declares those axes; the N-200 export always refuses). The sample 3+2 script
 * post writes the test block's program for test routers with two rotary axes, only with every
 * switch on and the grant; its program read back through our kinematics lands on the toolpaths.
 * Everything else is refused with its reason.
 */
import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { PluginHost } from '@/cam/plugin/host'
import { pluginRecord } from '@/cam/plugin/manifest'
import { planPartPost, runScriptPost } from '@/cam/plugin/posts'
import type { PluginRecord } from '@/cam/plugin/types'
import { SAMPLE_TEMPLATE } from '@/cam/post'
import { partFrameMoves, straightMoves, toVertical } from '@/cam/positional/convert'
import { fromMachine } from '@/cam/positional/kinematics'
import type { CamPart } from '@/cam/types'
import { MAIN_MACHINE, newMachineSetup } from '@/core/machines'
import { PLACEHOLDER_N200_MODEL } from '@/core/machineModel'
import type { AppData, MachineSetup, PositionalKinematics } from '@/core/types'
import { data } from './helpers'
import { blockPart, machine32 } from './positional-fixtures'
import { columnPart, rotaryOp } from './rotary-fixtures'

const POST = fs.readFileSync(path.resolve(import.meta.dirname, '../examples/plugins/positional-3plus2-post.js'), 'utf8')
const NOW = '2026-10-07T00:00:00.000Z'
const say = (s: string) => process.stdout.write(`  [3+2 post] ${s}\n`)
const codes = (issues: { code: string; severity: string }[]) => issues.filter((i) => i.severity === 'error').map((i) => i.code)

function install(code: string, grants: PluginRecord['grants'] = {}): PluginRecord {
  return { ...pluginRecord(code, 'test', NOW), grants, enabled: true }
}

/** A router with two rotary axes for 3+2 in the machine list, posting through the sample script post. */
function router32(d: AppData, layout: PositionalKinematics['layout'], first: 'A' | 'B' | 'C', second: 'A' | 'B' | 'C', extra: Partial<PositionalKinematics> = {}, travel: Record<string, [number, number]> = {}, post?: MachineSetup['post']): MachineSetup {
  const m = newMachineSetup(d, { name: `5-axis router ${layout}`, from: 'main' })
  const t = machine32(layout, first, second, extra, travel)
  m.profile = { ...m.profile, model: t.model, physical: t.physical }
  m.post = post ?? { kind: 'script', plugin: 'positional-3plus2-post', post: 'positional-3plus2' }
  d.machines = [...(d.machines ?? []).filter((x) => x.id !== m.id), m]
  return m
}

const allOn = (x: AppData) => (x.settings.features = { ...x.settings.features, scriptPostOutput: true, positionalPostOutput: true })

describe('M3.4 3+2 programs through a script post', () => {
  for (const [layout, first, second, extra] of [
    ['head-head', 'C', 'B', { tcp: false }],
    ['table-table', 'A', 'C', {}],
    ['table-head', 'C', 'B', { tcp: true }],
  ] as const) {
    it(`writes the test block for a ${layout} ${first}/${second} router: every move read back through the kinematics lands on the toolpath`, async () => {
      const d = data()
      const router = router32(d, layout, first, second, extra)
      const h = await PluginHost.start(install(POST))
      d.plugins = [{ ...install(POST, { machineOutput: true }), contributes: h.contributes }]
      const { part } = blockPart()
      // switches off: shown, not written, each switch named
      const off = planPartPost(d, router.id, part)
      expect(off.writable).toBe(false)
      expect(codes(off.issues)).toEqual(['POST_OUTPUT_OFF', 'POST_POSITIONAL_OFF'])
      allOn(d)
      const on = planPartPost(d, router.id, part)
      expect(codes(on.issues)).toEqual([])
      expect(on.writable).toBe(true)
      const text = (await runScriptPost(h, 'positional-3plus2', on.input)).text
      expect(text).toMatch(/^%\r\n\(Test block \(3\+2\)\)\r\n\(GENERATED BY CABINET STUDIO - NOT MACHINE-VALIDATED\)\r\nG21 G90 G17 G94 G54\r\n/)
      // read back: the locked angles, then X Y Z in work coordinates
      const k = router.profile.physical!.positional!
      const lines = text.split('\r\n')
      let worst = 0
      let n = 0
      let opIdx = -1
      let angles: [number, number] | null = null
      let mi = 0
      for (const l of lines) {
        const a = new RegExp(`^G0 ${first}(-?[\\d.]+) ${second}(-?[\\d.]+)$`).exec(l)
        if (a) {
          angles = [Number(a[1]), Number(a[2])]
          continue
        }
        if (/^\((Holes|Pocket)/.test(l)) {
          opIdx++
          mi = 0
          continue
        }
        const m = /^G[01] X(-?[\d.]+) Y(-?[\d.]+) Z(-?[\d.]+)/.exec(l)
        if (!m || opIdx < 0) continue
        const op = on.input.ops[opIdx]
        expect(op.positional).toBeTruthy()
        expect(angles).toEqual(op.positional!.angles.map((v) => Math.round(v * 1000) / 1000))
        const xyz = [Number(m[1]) + k.partAt.x, Number(m[2]) + k.partAt.y, Number(m[3]) + k.partAt.z]
        const back = fromMachine(k, { first: angles![0], second: angles![1] }, xyz, op.positional!.L)
        const tp = on.toolpaths[opIdx]
        const want = partFrameMoves(tp).moves.filter((q) => q.t === 'rapid' || q.t === 'feed')[mi++] as { x: number; y: number; z: number }
        worst = Math.max(worst, Math.hypot(back.tip[0] - want.x, back.tip[1] - want.y, back.tip[2] - want.z))
        n++
      }
      const turns = [...new Set(on.input.ops.map((o) => `${o.positional!.letters[0]}${o.positional!.angles[0]} ${o.positional!.letters[1]}${o.positional!.angles[1]}`))]
      say(`${layout} ${first}/${second}${k.tcp ? ' (tip control)' : ` (pivot ${k.pivot} mm)`}: ${n} moves read back through the kinematics, worst ${worst.toFixed(4)} mm (3 decimals written); angles ${turns.join(' / ')}`)
      expect(n).toBeGreaterThan(1000)
      // 3 decimals on X, Y, Z and on the angles (0.0005° at up to ~0.4 m from the pivot)
      expect(worst).toBeLessThan(0.005)
      // the axes turn (tool retracted first) wherever the angles change from one operation to the next
      const changes = on.input.ops.filter((o, i) => i === 0 || o.positional!.angles.join() !== on.input.ops[i - 1].positional!.angles.join()).length
      expect(text.match(/G53 G0 Z0\r\nG0 [ABC]/g)?.length).toBe(changes)
      // the same operation in its plane's own frame comes with it, arcs kept
      const pocket = on.input.ops.find((o) => o.name.startsWith('Pocket 2'))!
      expect(pocket.positional!.vertical.some((m) => m.t === 'arc')).toBe(true)
      const vt = straightMoves(toVertical(on.toolpaths[on.input.ops.indexOf(pocket)]))
      expect(vt[0]).toMatchObject({ t: 'rapid' })
      expect(pocket.positional!.plane!.name).toBe('30° chamfer')
      h.dispose()
    }, 120_000)
  }
})

describe('M3.4 3+2 output refused', () => {
  it('the N-200, the template post, a machine without 3+2 axes, axes too short, turned work mixed in, no grant', async () => {
    const d = data(allOn)
    const h = await PluginHost.start(install(POST))
    d.plugins = [{ ...install(POST, { machineOutput: true }), contributes: h.contributes }]
    const { part } = blockPart({ ops: 'holes' })
    // the N-200 (the main machine: woodWOP only)
    expect(planPartPost(d, MAIN_MACHINE, part).writable).toBe(false)
    // a router without 3+2 axes in its model: refused, and its post never gets a tilted move
    const plain = newMachineSetup(d, { name: 'Plain router', from: 'main' })
    plain.profile = { ...plain.profile, model: 'Plain router', physical: { ...structuredClone(PLACEHOLDER_N200_MODEL), placeholder: false } }
    plain.post = { kind: 'script', plugin: 'positional-3plus2-post', post: 'positional-3plus2' }
    d.machines = [...(d.machines ?? []), plain]
    const p0 = planPartPost(d, plain.id, part)
    expect(codes(p0.issues)).toEqual(['POST_POSITIONAL_MACHINE'])
    expect(p0.issues[0].message).toBe('Plain router: its machine model has no 3+2 (positional) axes.')
    expect(p0.input.ops.every((o) => o.tilted && !o.moves.length)).toBe(true)
    // the B axis tilts only 30°: the 45° chamfer and the upright back are out of reach
    const short = router32(d, 'head-head', 'C', 'B', {}, { B: [-30, 30] })
    const p1 = planPartPost(d, short.id, part)
    expect(codes(p1.issues)).toContain('POST_POSITIONAL_TRAVEL')
    expect(p1.issues.find((i) => i.code === 'POST_POSITIONAL_TRAVEL')!.message).toMatch(/Holes Ø8 \(45° chamfer\): it needs C0\.000° B45\.000° or C180\.000° B-45\.000°, outside the axes' travel/)
    // X too short for where the part sits
    const tight = router32(d, 'head-head', 'C', 'B', {}, { X: [0, 300] })
    expect(planPartPost(d, tight.id, part).issues.find((i) => i.code === 'POST_POSITIONAL_TRAVEL')!.message).toMatch(/The program moves X from [\d.]+ to [\d.]+ mm, outside its travel \(0 to 300 mm\)/)
    // the built-in template post: its text never carries the tilted moves
    const tm = router32(d, 'table-table', 'A', 'C', {}, {}, { kind: 'template', ...SAMPLE_TEMPLATE })
    const tp = planPartPost(d, tm.id, part)
    expect(codes(tp.issues)).toContain('POST_POSITIONAL_TEMPLATE')
    expect(tp.writable).toBe(false)
    expect(tp.templateText!.text).toContain('(Holes Ø8 (45° chamfer): TILTED PLANE (3+2) - NOT WRITTEN BY A TEMPLATE POST)')
    expect(tp.templateText!.text).not.toMatch(/G1 |G0 X|G81/)
    // a layout that cannot tilt the tool every way
    const bad = router32(d, 'head-head', 'B', 'C')
    expect(planPartPost(d, bad.id, part).issues.find((i) => i.code === 'POST_POSITIONAL_MACHINE')!.message).toMatch(/cannot tilt the tool every way round/)
    // turned work in the same program
    const good = router32(d, 'head-head', 'C', 'B')
    const { part: col, flutes } = columnPart()
    const mixed: CamPart = { ...part, rotary: col.rotary, entities: [...part.entities, ...col.entities.filter((e) => flutes.includes(e.id))], ops: [...part.ops, rotaryOp('wrap', { toolId: 't105', geometry: flutes })] }
    expect(codes(planPartPost(d, good.id, mixed).issues)).toContain('POST_POSITIONAL_MIXED')
    // the switches and the grant, as for any script post
    const ok = planPartPost(d, good.id, part)
    expect(codes(ok.issues)).toEqual([])
    const ungranted = structuredClone(d)
    ungranted.plugins = [{ ...d.plugins![0], grants: {} }]
    expect(codes(planPartPost(ungranted, good.id, part).issues)).toEqual(['POST_NO_GRANT'])
    const noSwitch = structuredClone(d)
    noSwitch.settings.features = { ...noSwitch.settings.features, positionalPostOutput: false }
    expect(codes(planPartPost(noSwitch, good.id, part).issues)).toEqual(['POST_POSITIONAL_OFF'])
    h.dispose()
  }, 120_000)
})
