import { BUILTIN_TEMPLATES } from './defaults'
import type { CabinetInstance, Job } from './types'

const tpl = (id: string) => {
  const t = BUILTIN_TEMPLATES.find((x) => x.id === id)
  if (!t) throw new Error(`missing template ${id}`)
  return t
}

const cab = (id: string, number: string, name: string, templateId: string, patch: (p: CabinetInstance['params']) => void = () => {}, qty = 1): CabinetInstance => {
  const params = JSON.parse(JSON.stringify(tpl(templateId).params)) as CabinetInstance['params']
  patch(params)
  return { id, number, name, templateId, qty, params, overrides: {} }
}

/** Small kitchen used for golden files, screenshots and the "Load sample job" button. */
export function sampleJob(): Job {
  return {
    id: 'job-sample',
    number: 'J1042',
    name: 'Cohen kitchen - sample',
    customer: 'Cohen',
    notes: 'Sample job generated by Cabinet Studio. Placeholder tools: do not run on the machine.',
    createdAt: '2026-10-03T00:00:00.000Z',
    updatedAt: '2026-10-03T00:00:00.000Z',
    cabinets: [
      cab('cab-b1', 'B1', 'Base 600, 2 doors', 'tpl-base-2door'),
      cab('cab-b2', 'B2', 'Base 450, 1 door', 'tpl-base-1door', (p) => {
        p.doors.hingeSide = 'right'
      }),
      cab('cab-b3', 'B3', 'Sink base 800', 'tpl-sink-base'),
      cab('cab-w1', 'W1', 'Wall 600, 2 doors', 'tpl-wall-2door', () => {}, 2),
    ],
  }
}
